CREATE GLOBAL CUBE [Autopartes_dim]
STORAGE 'C:\Temp\Autopartes_dim\Autopartes_dim.cub'
FROM [Autopartes Dim_cube]
(
    -- fact entradas
    MEASURE [Autopartes Dim_cube].[Almacen],
    MEASURE [Autopartes Dim_cube].[Cantidad],
    MEASURE [Autopartes Dim_cube].[Cantidad Partidas],
    MEASURE [Autopartes Dim_cube].[Cantidad U Med Inv],
    MEASURE [Autopartes Dim_cube].[Count Entradas],
    MEASURE [Autopartes Dim_cube].[Fact Entradas Count],
    MEASURE [Autopartes Dim_cube].[Partida],
    MEASURE [Autopartes Dim_cube].[Pct Descuento],
    MEASURE [Autopartes Dim_cube].[Pct Descuento Global],
    MEASURE [Autopartes Dim_cube].[Pct Impuesto],
    MEASURE [Autopartes Dim_cube].[Precio],
    MEASURE [Autopartes Dim_cube].[Total],
    MEASURE [Autopartes Dim_cube].[Total Descuento],
    MEASURE [Autopartes Dim_cube].[Total Descuento Detalle],
    MEASURE [Autopartes Dim_cube].[Total Detalle],
    MEASURE [Autopartes Dim_cube].[Total Importe],
    MEASURE [Autopartes Dim_cube].[Total Importe Detalle],
    MEASURE [Autopartes Dim_cube].[Total Impuesto],
    MEASURE [Autopartes Dim_cube].[Total Impuesto Detalle],
    MEASURE [Autopartes Dim_cube].[Ubicacion],
    
    -- fact facturas
    MEASURE [Autopartes Dim_cube].[Almacen - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Cantidad - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Cantidad Partidas - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Cantidad U Med Inv - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Count Facturas],
    MEASURE [Autopartes Dim_cube].[Fact Facturas Count],
    MEASURE [Autopartes Dim_cube].[Partida - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Pct Descuento - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Pct Descuento Global - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Pct Impuesto - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Precio - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Rac IVA],
    MEASURE [Autopartes Dim_cube].[Total Descuento Detalle - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Total Descuento Factura],
    MEASURE [Autopartes Dim_cube].[Total Detalle - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Total Factura],
    MEASURE [Autopartes Dim_cube].[Total Importe Detalle - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Total Importe Factura],
    MEASURE [Autopartes Dim_cube].[Total Impuesto Detalle - Fact Facturas],
    MEASURE [Autopartes Dim_cube].[Total Retencion],

    -- fact salidas
    MEASURE [Autopartes Dim_cube].[Almacen - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Cantidad - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Cantidad Partidas - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Cantidad U Med Inv - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Count Salidas],
    MEASURE [Autopartes Dim_cube].[Fact Salidas Count],
    MEASURE [Autopartes Dim_cube].[Partida - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Pct Descuento - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Pct Descuento Global - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Pct Impuesto - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Precio - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Total - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Total Descuento - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Total Descuento Detalle - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Total Detalle - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Total Importe - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Total Importe Detalle - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Total Impuesto - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Total Impuesto Detalle - Fact Salidas],
    MEASURE [Autopartes Dim_cube].[Ubicacion - Fact Salidas],

    -- dimensiones
    DIMENSION [Autopartes Dim_cube].[Dim Articulos],
    DIMENSION [Autopartes Dim_cube].[Dim Clientes],
    DIMENSION [Autopartes Dim_cube].[Dim Condicion Pago],
    DIMENSION [Autopartes Dim_cube].[Dim Medio Embarque],
    DIMENSION [Autopartes Dim_cube].[Dim Moneda],
    DIMENSION [Autopartes Dim_cube].[Dim Sub Entradas],
    DIMENSION [Autopartes Dim_cube].[Dim Sub Facturas],
    DIMENSION [Autopartes Dim_cube].[Dim Sub Salidas],
    DIMENSION [Autopartes Dim_cube].[Dim Time],
    DIMENSION [Autopartes Dim_cube].[Dim Vendedores]
)